### ISSUE TITLE
Files referenced in main property of bower.json do not exist

### ISSUE THREAD

**Issue by hzpz** [ruhley/angular-color-picker#10]
Thank you very much for fixing the issues I reported yesterday so quickly! However, wiredep still does not work and I just figured out why: the files referenced in the main property of bower.json do not exist. bower.json references `angular-color-picker.js` but the filename is actually `angularjs-color-picker.js`. The same applies to the css file.

**Comment by ruhley** [comment]
Fixed in f53634167b871dbd45e8f1a744c750c82bff3f3c and released in [v0.3.4](https://github.com/ruhley/angular-color-picker/releases/tag/v0.3.4).
