### ISSUE TITLE
Console error when setting format option in HTML

### ISSUE THREAD

**Issue by bouks** [ruhley/angular-color-picker#102]
Hi.

When assigning options in HTML like this:
`<color-picker class='col-sm-1' ng-model="entity.color" options="{format:'hex',,swatchOnly:true}" /></color-picker>`

I get a compile error:
`Error: [$compile:nonassign] http://errors.angularjs.org/1.5.8/$compile/nonassign?p0=%7Bformat%3A'hex'%2CswatchOnly%3Atrue%7D&p1=options&p2=colorPicker`

But it's working... :)

colorpicker: 2.4.1
tinycolor: 1.4.1
angular: 1.5.8

**Comment by ruhley** [comment]
Fixed in commit 32d8857d80e2835568f20c0fbdb58cf31c9bd68c and released in [v2.4.2](https://github.com/ruhley/angular-color-picker/releases/tag/v2.4.2)
