### ISSUE TITLE
Multiple Color Picker instances

### ISSUE THREAD

**Issue by kirdua1** [ruhley/angular-color-picker#106]
Hi,

I need to have multiple instances of the color picker directive on the same page. I've noticed though that when I set unique ng-models for each one. If I open one then it starts working with the other one and displaying the hex value in the wrong field.

`<color-picker
        ng-model="navbarColor"
        options="options"
        api="api"
        event-api="eventApi">
      </color-picker>`

`<color-picker
        ng-model="navbarFontColor"
        options="options"
        api="api"
        event-api="eventApi">
      </color-picker>`

`$scope.options = {
            required:false,
            disabled:false,
            round:false,
            format:'hex',
            hue:false,
            alpha:false,
            swatch:true,
            swatchPos:'left',
            swatchBootstrap:true,
            swatchOnly:false,
            pos:'bottom-left',
            case:'lower',
            inline:false,
            placeholder:'',
            close:{
              show:true,
              label:'Close',
              class:''
            }
        };`

Is there a way to have multiple on the same page?

**Comment by ruhley** [comment]
The `api` attribute is **not** required, but if you do supply it each color picker needs a separate api object.
