### ISSUE TITLE
update ngModel dirty flag when color is changed

### ISSUE THREAD

**Issue by ncourtial** [ruhley/angular-color-picker#11]
Hi,
When you change color in color-picker, model dirty flag isn't updated.
Maybe adding the following line in ngModel watch would correct the problem :
if($scope.isValid)
control[0].$setDirty() 

Cheers,
Nathan

**Comment by ruhley** [comment]
Fixed in 6394a3562775838c3873f3db1f5fbf0380494393 and released in [v0.3.5](https://github.com/ruhley/angular-color-picker/releases/tag/v0.3.5).

Thanks for helping improve the library
