### ISSUE TITLE
Require.js can't find "tinycolor2"

### ISSUE THREAD

**Issue by TheWizz** [ruhley/angular-color-picker#110]
When using RequreJS to load dependencies, loading the coloepicker, results in this error:

Error: Script error for "tinycolor2", needed by: angularColorPicker

I use Bower as the package manager, and under Bower it seems the package is called just "tinycolor", while it's called "tinycolor2" under npm.

How can I resolve this discrepancy so that the color picker loads "tinycolor" and doesn't complain about not finding "tinycolor2"?

-JM

**Comment by ruhley** [comment]
Hi @TheWizz,

I don't have any experience with RequireJS so I may not be much of a help. You can try looking into another ticket with a similar problem #66. You could also try configuring RequireJS to look for tinycolor2

```js
requirejs.config({
       paths:
           tinycolor2: 'bower_components/angular-color-picker/dist/angular-color-picker.min'
       }
   });
```

**Comment by TheWizz** [comment]
Yes, I managed to load the "tinycolor2" version and apply it as a global like this:

```
require(['angular','tinycolor2','ngMaterial', 'uiRouterDefault'], function(angular, tinycolor) {
	window.tinycolor = tinycolor;	// Expected as global by colorPicker, loaded subsequently
```

Having it available through Require under the name 'tinycolor2' while also assigning it as a window global under the name tinycolor seemed to make everybody happy.

-JM
