### ISSUE TITLE
Tab focus opens panel, tab blur does not close it.

### ISSUE THREAD

**Issue by ashconnell** [ruhley/angular-color-picker#113]
If you Tab from a previous input into the color picker, the grid panel opens up. If you Tab again the panel does not close. You need to specifically click to outside to close it.

**Comment by ruhley** [comment]
Fixed in commit d6c286a939b76bc863f67658531f36f312098d39 and released in [v2.4.7](https://github.com/ruhley/angular-color-picker/releases/tag/v2.4.7). I also added closing the panel using the escape key.

**Comment by ashconnell** [comment]
@ruhley you beat me to it! I created this as a reminder for me to make a PR. Cheers!
