### ISSUE TITLE
color-picker-grid not working in Safari

### ISSUE THREAD

**Issue by CarlsBad505** [ruhley/angular-color-picker#114]
The color-picker-grid won't work properly in the Safari browser. More specifically, when you hit the ng-focus="show()" function which turns your $scope.visible variable from true to false isn't working in Safari. Can you attempt to fix please?

**Comment by ruhley** [comment]
Hi @CarlsBad505,

I don't have immediate access to Mac, but I will try to get a hold of one as soon as possible.

**Comment by CarlsBad505** [comment]
Do you work on a PC? You can download that browser for PC.

**Comment by Fernker** [comment]
Don't download Safari for PC.  It hasn't been developed/supported for years on PC.  Safari can only be tested on a Mac.

**Comment by warpdesign** [comment]
@CarlsBad505 Do you have a specific example (with code): maybe I could help as I have access to a Mac.

**Comment by CarlsBad505** [comment]
@warpdesign According to this website, it might be futile to try since it appears that color input fields are not supported in Safari 9.1, but supported on version 10. Check it out here: http://caniuse.com/#search=color%20input

This isn't necessarily something that's particular to my code, rather than an issue with browser compatibility. I'd suggest you create a pull request if you want to attempt to fix it! Thanks

**Comment by CarlsBad505** [comment]
@warpdesign Nicolas, it doesn't appear to work in Safari 10 either, unfortunately. I just tried it out.

**Comment by ruhley** [comment]
@CarlsBad505 I got hold of a Mac Mini running OS X v10.9.5 and Safari 9.0 and everything seems to work fine for me. We may need more details of what you are running or some code with it breaking.

**Comment by warpdesign** [comment]
@ruhley yes, it seems to work, that's why I asked @CarlsBad505 for an example to reproduce the problem :)

**Comment by ruhley** [comment]
There hasn't been an update on this issue in a while and the exact issue cannot be replicated. If you still need help then please re-open the issue.
