### ISSUE TITLE
Touch events not working in Chrome (desktop in device mode) and in Android webview

### ISSUE THREAD

**Issue by Sebastien-G** [ruhley/angular-color-picker#115]
Hi,

The color-picker (tested with v2.4.5, v2.4.6 and v2.4.7) does not respond when in Google Chrome in device mode (Windows 10 and Mac OS X). Whatever the color you pick, it turns to black. The color picker works fine when _not_ in device mode.
The color picker also works fine on iOS in webview (Ionic app), but it also breaks in Android webview (same Ionic app).

You can replicate this behaviour with the demo page at: https://ruhley.github.io/angular-color-picker/
Just open the page in Chrome, open the Dev Tools and toggle the device toolbar.

**Comment by ruhley** [comment]
Fixed in commit 16eff08 and released in v2.4.8

**Comment by Sebastien-G** [comment]
Hi ruhley,

I can confirm that the bug is fixed. It now works in the browser (Chrome) in device mode. It also works in my webview on Android.

Thank You so much for addressing this issue so quickly, it really helps me out to meet a deadline! I owe you a beer (when are you coming to Paris?)
