### ISSUE TITLE
Access to the scope ?

### ISSUE THREAD

**Issue by warpdesign** [ruhley/angular-color-picker#116]
I am using colorPicker inside a ng-repeat, like this:

    <div ng-repeat="obj in objects">
      <color-picker ng-model="obj.color" ... />
    </div>

It's working as expected, but the problem is that I need to have access to the current obj from my onChange event and I don't think it's possible right now: change callback only passes the $event, color and api object.

Any idea how I could do that ?

**Comment by ruhley** [comment]
I have added a new feature `api.getScope()` which should give you what you need. Released in [v2.5.0](https://github.com/ruhley/angular-color-picker/releases/tag/v2.5.0)

**Comment by warpdesign** [comment]
👍 
Thanks!
