### ISSUE TITLE
Round "Color picker": inability to choose a black color. "Hue option" doesn't help. Thank's.

### ISSUE THREAD

**Issue by dmytrodemchenko** [ruhley/angular-color-picker#119]
<img width="753" alt="screen shot 2016-10-11 at 12 33 17 pm" src="https://cloud.githubusercontent.com/assets/11888586/19265733/f6d918be-8fae-11e6-9f61-870ee5ea9ffd.png">

**Comment by mathben** [comment]
I suggest to add saturation option like hue.

**Comment by ruhley** [comment]
I have added saturation and lightness options in v2.6.0
