### ISSUE TITLE
$touched not working with angular-color-picker

### ISSUE THREAD

**Issue by Futursky** [ruhley/angular-color-picker#120]
Default angular field property $touched not working with angular-color-picker. For example when I change my color input then remove color $touched should be true, $pristine: false and $dirty: true but it does not.
https://www.dropbox.com/s/loynqb6gl3006ov/Screenshot%202016-10-15%2021.51.45.png?dl=0

**Comment by ruhley** [comment]
This has been released in v2.6.0
