### ISSUE TITLE
Round Color Picker : No Option to select darker colors

### ISSUE THREAD

**Issue by manashemrajani** [ruhley/angular-color-picker#128]
When the shape of color picker is made round, the option to choose darker colors like black or brown is not present. It would be great to have that option as these are the basic colors.

**Comment by ruhley** [comment]
Try using the `lightness` option to allow for selecting lighter or darker colors.

**Comment by manashemrajani** [comment]
Thanks Alot! I had missed the lightness option! Amazing module ruhley.
