### ISSUE TITLE
swatch color vs square color

### ISSUE THREAD

**Issue by Tyre88** [ruhley/angular-color-picker#136]
Hello, the swatch color and the picker color doesn't match. See screenshot. 

The problem is that inside the square the color is brighter then what is shown in the swatch. 

Is there a way to fix this?

![swatch](https://cloud.githubusercontent.com/assets/4730856/21634717/89eec58a-d259-11e6-9f9d-d4f8e8a01897.png)

**Comment by ruhley** [comment]
This is because lightness is not shown in that color picker. I have attempted a fix in v3.0.0 which should make the color closer to the swatch.
