### ISSUE TITLE
Direct access to individual colour values

### ISSUE THREAD

**Issue by ashthespy** [ruhley/angular-color-picker#137]
Would it be possible to directly get individual `r`,`g`,`b` or `hue`,`saturation`,`lightness` values?
I currently re-parsing the  `$scope.color$` but am wondering what the right way to achieve this would be

EDIT: 
Please don't bother, forked and added a `rawHsl`  format option and passed the `tinycolor.toHsl()` object directly. 
PS: quick hacky work -  a0d5d3776b2cc4b552884ecfe1d8004fd6a33182

**Comment by ruhley** [comment]
@ashthespy I will add a `raw` format option which will pass back the tinycolor object which you can do as you please

**Comment by ashthespy** [comment]
Consider this under the label 'Help Wanted'
I would like to adjust the `lightness` via an external slider while maintaining a two way binding between the slider and the actual color object.

Currently, I have setup two watches (one for the slider, one for the color object) to update each other. However, this leads to recursive updating. Any suggestions be to avoid the recursive updates?
[Plunker](https://plnkr.co/edit/SZt5QnpKdd3pCr430Nrx)

**Comment by ruhley** [comment]
This is one of the big reasons I generally try to avoid using `$watch`. See my [Plunker](https://plnkr.co/edit/JNxx6YwjYECCrfhLXhXu?p=preview) using `onChange` events for both the slider and the color picker.

Side Note: There must be a bug in the color picker that requires the use of `$scope.$applyAsync()` in this plunker. I have created another ticket to investigate this.

**Comment by ruhley** [comment]
I have released the `raw` format option in v3.0.0
