### ISSUE TITLE
Gradient shown below picker in Firefox (Windows)

### ISSUE THREAD

**Issue by scottiemc7** [ruhley/angular-color-picker#143]
Firefox for Windows, version 50.1.0. I tried the latest on my site and see the same thing. Chrome (Windows), Chrome (Mac), and Safari all look fine.

<img width="929" alt="screen shot 2017-01-22 at 3 05 02 pm" src="https://cloud.githubusercontent.com/assets/1521455/22187095/77e30cc4-e0b5-11e6-8e5d-5fbe2568be1b.png">

**Comment by ruhley** [comment]
Fixed and released in v3.0.1
