### ISSUE TITLE
"green" is an accepted value but "red" is not

### ISSUE THREAD

**Issue by jooleeunc** [ruhley/angular-color-picker#144]
I created a JSBin of a basic demo of the color picker with $error object.

https://jsbin.com/fatinapana/1/edit?js,output

You'll see that "green" is valid while "red" is not.  It's because of Line 42:

https://github.com/ruhley/angular-color-picker/blob/master/src/scripts/controller.js#L42

What's the purpose of this if check "newValue.length > 4"?  Could we remove it?

**Comment by ruhley** [comment]
I think the limit of 4 characters was put in an early version as a work around to another problem. I have removed it as it is no longer required

**Comment by jooleeunc** [comment]
Thanks for such a quick response!
