### ISSUE TITLE
Input field should respect specified format.

### ISSUE THREAD

**Issue by jooleeunc** [ruhley/angular-color-picker#145]
Even though I specify "hex" as the format, I can specify "green" and it will accept as a valid format.  It seems like if I specify "hex", the color picker should validate the format and set form validity to false.

If you think this is a good idea, I can start working on a PR to add this feature.

**Comment by ruhley** [comment]
I have added a `restrictToFormat` option to allow for either way

**Comment by jooleeunc** [comment]
Awesome! Thanks a ton!
