### ISSUE TITLE
color sliders not working right

### ISSUE THREAD

**Issue by ayhanyildiz** [ruhley/angular-color-picker#146]
Color slider color options gets overwritten when colors picked. If you slide to black or white you lose all colors.

**Comment by ruhley** [comment]
@ayhanyildiz This has always been a grievance of mine about the [tinycolor](https://github.com/bgrins/TinyColor) library.

**Comment by ayhanyildiz** [comment]
I hear you. If I can fix, i will send you PR

**Comment by ruhley** [comment]
I have finally fixed this one in commit 92bf25b and released in [v3.4.5](https://github.com/ruhley/angular-color-picker/releases/tag/v3.4.5)

**Comment by ayhanyildiz** [comment]
great thanks!
