### ISSUE TITLE
Hide events don't seem to respect their properties

### ISSUE THREAD

**Issue by aaw5017** [ruhley/angular-color-picker#147]
Hi there,

I was recently dealing with a bug in IE11 where the "Clear" button was not working properly. I worked around this issue by setting `hide: { blur: false };`. However, the picker popup still seems to close whenever a blur, click, or escape event is fired, even if I set those properties to `false`. This issue seems to occur in all browsers. Not a huge deal, just wanted to let you know!

Thanks for the awesome library!

**Comment by ruhley** [comment]
Apparently this is a known IE bug - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101237/. I have changed from focus/blur to focusin/focusout like that page suggests.
