### ISSUE TITLE
Color picker hue looks empty on IE

### ISSUE THREAD

**Issue by olezt** [ruhley/angular-color-picker#148]
Color picker hue looks empty on InternetExplorer. (tested on IE11)

**Comment by ruhley** [comment]
The color picker uses linear gradients to display these. Are you able to force IE to render using the latest standards? Adding the following tag to the html `<head>` block should fix it up.

`<meta http-equiv="X-UA-Compatible" content="IE=Edge" />`

**Comment by olezt** [comment]
Sorry I don't have the time to test this since I already proceed with another colorpicker, but the problem is visible also in your gh-page demo, so you can give it a try there.

**Comment by johngomersall** [comment]
I've seen this too. It looks like the height:100% style isn't working on the color-picker-overlay. I'm working around by hard-coding the height to 150px.

**Comment by ruhley** [comment]
@johngomersall Thanks for the fix. Released in v3.1.2
