### ISSUE TITLE
Use addOn component

### ISSUE THREAD

**Issue by benoror** [ruhley/angular-color-picker#15]
Hi, I really like your implementation and the fact that it doesn't depend on jQuery, as an alternative to [buberdds/angular-bootstrap-colorpicker](https://github.com/buberdds/angular-bootstrap-colorpicker/)

Since I use bootstrap a lot I would like to have the same look-and-feel for all my controls, therefore I would like to use an **addOn component** with the color, [as shown here](http://mjolnic.com/bootstrap-colorpicker/) (2nd example).

Is it currently possible?

**Comment by ruhley** [comment]
Do you mean the [bootstrap input groups](http://getbootstrap.com/components/#input-groups-basic)? If so I can add it as an option.

**Comment by benoror** [comment]
Yes exactly!

In case you're interested I contribute making examples for this form-generation library: http://angular-formly.com/

**Comment by ruhley** [comment]
This has been release in [v0.5.0](https://github.com/ruhley/angular-color-picker/releases/tag/v0.5.0) as the ```color-picker-swatch-bootstrap``` option which defaults to ```true```.

**Comment by benoror** [comment]
Wow thanks @ruhley , here is the example with angular-formly (it will be added to the main webpage soon):

http://jsbin.com/yogiye/4/edit

**Comment by ruhley** [comment]
Sweet. Thanks for putting this in your library examples and giving it some exposure.

**Comment by benoror** [comment]
Actually it's not mine, but I contribute. Anyway I like your colorpicker since it plays nice with angular ui bootstrap and doesn´t requiere JQuery

**Comment by benoror** [comment]
Take a look: https://github.com/formly-js/angular-formly-website/pull/28#issuecomment-109073885

Some ideas how can I improve the example?

**Comment by benoror** [comment]
It's merged, look: http://angular-formly.com/#/example/integrations/colorpicker

BTW, can you spot some pixels to the right of the 3rd example? (when `color-picker-swatch-only="true"`)
