### ISSUE TITLE
Support for touch events

### ISSUE THREAD

**Issue by mcierzniak** [ruhley/angular-color-picker#155]
Hi!
How much work do you think it would take to make this picker more mobile-friendly ? Right now it seems like the picker does not work with the touch events at all. I tried to pick some color on my phone and it does not seem to interact with the picker correctly. Maybe I could look at the code and eventually send some pull request for that.

**Comment by ruhley** [comment]
@mcierzniak There are touch events registered in this library - https://github.com/ruhley/angular-color-picker/blob/master/src/scripts/controller.js#L254-L256

Can you give me more details on the problem and what mobile device and browser you are using

**Comment by ruhley** [comment]
Closing as there has not been any updates
