### ISSUE TITLE
Color picker selector seems stuck to the left with { round: false }

### ISSUE THREAD

**Issue by JSti** [ruhley/angular-color-picker#159]
The small circle indicating the current color seems to be stuck to the left of the color selection area, when using { round: false }. 

![image](https://user-images.githubusercontent.com/777245/28752880-0f42873a-752a-11e7-9100-60ce2c38172f.png)

When using { round: true } the issue does not occur (indicator moving along with selection).

![image](https://user-images.githubusercontent.com/777245/28752892-5334ab94-752a-11e7-86d7-183d3e299911.png)

Issue visible on demo page as well.

**Comment by ruhley** [comment]
Fixed in commit 144d25fb678ab9279c98305dd7d0efab46122a05 and released in [v3.4.1](https://github.com/ruhley/angular-color-picker/releases/tag/v3.4.1)
