### ISSUE TITLE
Unable to Use hexString Format with restrictToFormat

### ISSUE THREAD

**Issue by myerscw** [ruhley/angular-color-picker#173]
If the format of the picker is set to "hexString" and restrictToFormat is true, isColorValid returns false because of: 
```
if (isValid && this.options.restrictToFormat) {
  isValid = color.getFormat() === this.options.format;
}
```
tinycolor returns the format from getFormat() as "hex" for a value like "#ff0000" which will get compared to "hexString".

Using tinycolor2 1.4.1 and angular-color-picker 3.4.4

**Comment by ruhley** [comment]
This has been fixed in commit dbc042e and released in [v3.4.5](https://github.com/ruhley/angular-color-picker/releases/tag/v3.4.5)
