### ISSUE TITLE
Clicking on swatch when disabled still opens a UI

### ISSUE THREAD

**Issue by jlynde** [ruhley/angular-color-picker#174]
If I set the option to disabled: true and then click on the swatch on the [demo page](https://ruhley.github.io/angular-color-picker/) the GUI still pops up.  The user cannot change anything but it still pops up anyway.  I was not expecting that to happen when the picker was disabled.

**Comment by ruhley** [comment]
This has been fixed in commit 1e15322and released in [v3.4.5](https://github.com/ruhley/angular-color-picker/releases/tag/v3.4.5)
