### ISSUE TITLE
Angular loaded more than once error

### ISSUE THREAD

**Issue by TingAli** [ruhley/angular-color-picker#175]
Getting "WARNING: Tried to load angular more than once." in the dev console when opening any page. I've followed the instructions to the bullet, any ideas what's wrong?

**Comment by ruhley** [comment]
This usually occurs when some kind of resource (html, js, css file) is trying to be loaded, but results in a 404. If your setup redirects all 404 errors to the base url then it will load the index.html file again, which will load angular again. Is there any 404 errors in the dev console?

**Comment by ruhley** [comment]
I am closing this issue as I do not think it pertains to this library. Please re-open if you feel otherwise
