### ISSUE TITLE
Alpha value saving to model but not displaying back

### ISSUE THREAD

**Issue by visiperl** [ruhley/angular-color-picker#18]
I'm setting the alpha property to true and it will allow me to adjust the alpha value and it display properly initially, however, when I load the value back from local storage (which it is storing correctly), it looses the alpha property.  Wanted to see if you knew of something I might not have set correctly before I started digging into the code and debugging.

Oh, also, whenever I try to assign something like settings.backgroundColor against the ng-model property of the color-picker directive, it won't work.  I have to reassign all my settings.xxx to straight backgroundColor type variables.  So it looks like there is an issue when the ngModel is referencing a property of an object.

**Comment by ruhley** [comment]
Hi @visiperl - Are you able to create a codepen/jsfiddle of your problem. That would help greatly.

**Comment by visiperl** [comment]
Hi,

I'm not to familiar with these newer online editing environments, so 
please forgive me if I didn't do this exactly as it should have been 
done.  However, here's an example of what I'm seeing.

http://codepen.io/anon/pen/VLGZYZ

I essentially copied all the source references from my bower_components 
folder up to my server and then modified the links so they pointed to that.

Thank you for your assistance,

Ken

**Comment by ruhley** [comment]
Fixed in commit e17bf0219afbba398657918c48670b7dec4ae7b6 and release in [v0.6.3](https://github.com/ruhley/angular-color-picker/releases/tag/v0.6.3). Sorry about the slow turn around. I have been away. The codepen example was great and helped a lot.

**Comment by benoror** [comment]
:+1:
