### ISSUE TITLE
Two way binding not working

### ISSUE THREAD

**Issue by hilnius** [ruhley/angular-color-picker#19]
Hi, Apparently the two way binding is broken.
What I mean is that typing in the input does not properly change the selected color.

jsFiddle example : http://jsfiddle.net/xnq6fhr2/

It comes from the if ($scope.isValid) which returns false when there are 5 hex characters and someone's typing the 6th.

**Comment by ruhley** [comment]
Thanks for the fiddle. It certainly seems to be the isValid method. I probably won't have time this week to look into it. If you need it sooner then you may want to create a pull request.
