### ISSUE TITLE
No tiny.js file 

### ISSUE THREAD

**Issue by MateenKadwaikar** [ruhley/angular-color-picker#21]
I was not able to find tiny.js file after cloning the file.

**Comment by ruhley** [comment]
Did you install ```angular-color-picker``` through bower?

**Comment by benoror** [comment]
I'm having the same issue when installing via NPM, I have an idea on how to sort it out, I will open another issue with the details

**Comment by ruhley** [comment]
Please reopen if you are still having this problem @MateenKadwaikar

**Comment by MateenKadwaikar** [comment]
@ruhley no I don't have any problem now.
