### ISSUE TITLE
Add Main in Package.json

### ISSUE THREAD

**Issue by origin1tech** [ruhley/angular-color-picker#24]
Any chance I could get you to add a "main": "./path/to/angular-color-picker.js" in the package.json? This would then allow import for ES6 modules. Packages should typically have a main anyway, so its a good idea regardless.

To be clear also point the main to the uncompressed file as in the user/devs build process he'll be compiling the modules for output and will need it in the uncompressed state.

**Comment by ruhley** [comment]
Fixed in commit 2142f4129c5222a7406934b98ec4add9d599bc31 and released in [v0.6.5](https://github.com/ruhley/angular-color-picker/releases/tag/v0.6.5).

**Comment by origin1tech** [comment]
thx @ruhley
