### ISSUE TITLE
This is not working in Internet Explore 11

### ISSUE THREAD

**Issue by lilan123** [ruhley/angular-color-picker#26]
Hi, This is not working in IE 11

**Comment by lilan123** [comment]
Is there any solution for that?

**Comment by ruhley** [comment]
Sorry about the delay, I was getting a machine with IE11. What exactly is wrong with it? I have a minor display issue with the swatch not being the full height, but apart from that it is fully functional. I have fixed up the display issue in [v0.6.6](https://github.com/ruhley/angular-color-picker/releases/tag/v0.6.6).

**Comment by lilan123** [comment]
Thanks a lot ruhley, it works fine with this version.
