### ISSUE TITLE
color-picker-swatch-only="true" does not work properly

### ISSUE THREAD

**Issue by frejfrej** [ruhley/angular-color-picker#27]
On your demo site, the color-picker-swatch-only="true" shows only the swatch, but when I use the latest version, the text label remains visible
tested on version 0.6.6

**Comment by ruhley** [comment]
Thanks for reporting the issue. I did break it in the v0.6.6 release. Fixed in commit 9bcefba92e1bbf6309fe51376d53c2a0f84cc48a and released in [v0.6.7](https://github.com/ruhley/angular-color-picker/releases/tag/v0.6.7)
