### ISSUE TITLE
Color Picker does not work in mobile devices

### ISSUE THREAD

**Issue by lilan123** [ruhley/angular-color-picker#29]
Hi Ruhley, 

Selecting color is not working in mobile devices and only that issue is there as I investigated. it is really fantastic, If you can change it to work in mobile devices as well. 

Thanks in advance.

Regards,
Lilan

**Comment by ruhley** [comment]
Hi @lilan123,

The only problem I could find was on chrome for mobiles. I have fixed the issue in commit b8c6d81f7ddcc13cc4e897c3bb86f4ab9436d159 and released in [v0.6.8](https://github.com/ruhley/angular-color-picker/releases/tag/v0.6.8).
