### ISSUE TITLE
ng-init property

### ISSUE THREAD

**Issue by sutkovoy** [ruhley/angular-color-picker#32]
Hi! For now color-picker not support ng-init value. So i can not use update functionality. Can u fix it? Thx.

**Comment by ruhley** [comment]
Hi @sutkovoy. I have never used ```ng-init``` and am struggling to understand how it would be used in the color picker. Are you able to give an example of what you are trying to do? There is a [codepen](http://codepen.io/ruhley/pen/QjrGrG) example that you could fork.
