### ISSUE TITLE
Change swatch size

### ISSUE THREAD

**Issue by saaqibz** [ruhley/angular-color-picker#37]
Thanks for creating this directive!

Can you give some guidance on how to cleanly change the size of the color swatch? that remains on the page?

**Comment by saaqibz** [comment]
Just in case anyone is looking for a workaround, I managed to change the size with the following. Adjust width and height as you need.

            .color-picker-swatch-only,
            .color-picker-swatch {
                height:20px;
                width: 20px;
                margin:0;
                padding:0;
                display:inline-block;
            }

**Comment by ashthespy** [comment]
I am attempting to change the `height` of the swatch, but seem unable to do so with the workaround you posted @saaqibz . Any ideas? [Plnkr](https://plnkr.co/edit/U2w0tLhp8cBtehTbxAqV?p=preview)

**Comment by ruhley** [comment]
@ashthespy - Try adding `!imporant` to the height rule.
