### ISSUE TITLE
BUG: Impossible to choose pure white/black/whatever from corners

### ISSUE THREAD

**Issue by cahva** [ruhley/angular-color-picker#38]
Hi,

There seems to be a problem when you want to choose for example #fffff (top-left corner). Its always close like #FBFBFB. Same applies to all 4 corners. You can try this at your own demo page at http://ruhley.github.io/angular-color-picker/

**Comment by ruhley** [comment]
This is something that has always bothered me. I will model my solution after http://mjolnic.com/bootstrap-colorpicker/

**Comment by ruhley** [comment]
I have implemented a new solution in commit 676cea3932cedbd121be58ad26ea7a337d9343c8 and released in [v0.7.0](https://github.com/ruhley/angular-color-picker/releases/tag/v0.7.0). I think it is a much better experience using it now.
