### ISSUE TITLE
Fix package.json `main` field

### ISSUE THREAD

**Issue by mightydes** [ruhley/angular-color-picker#40]
For now used:
```
  "main": [
    "angularjs-color-picker.js",
    "angularjs-color-picker.css"
  ]
```
[source](https://github.com/ruhley/angular-color-picker/blob/master/package.json#L5)

For properly work with, for example, [browserify](https://github.com/substack/node-browserify)
should be:
```
  "main": "angularjs-color-picker.js"
```
https://docs.npmjs.com/files/package.json#main

Do you need a pull request for it?

**Comment by ruhley** [comment]
Merged your pull request. :+1:
