### ISSUE TITLE
onchange event

### ISSUE THREAD

**Issue by arindrajitb** [ruhley/angular-color-picker#47]
Hi there,
is there an onChange event available in the directive? I could not find one. If not do you have any plan to introduce one?
regards
Ari

**Comment by ruhley** [comment]
Currently if I need to do something on change I use ```$watch()``` (e.g. https://github.com/ruhley/angular-color-picker/blob/master/examples/app.js#L9-L11). 

I could easily add in an onchange event though if you would prefer that.

**Comment by arindrajitb** [comment]
i'm using $watch at this point to get it going. But watch doesn't
distinguish between programmatic change and change by user. So i had to use
two sets of variable to identify whether change is coming from UI or from
back end. overall its pretty cumbersome as my page has two/three of this
directive.
It would be easier to use if the directive comes with a onchange similar
behavior like ng-change.
Also watch get fired multiple time when cursor is moved over the color
selection pallet. Again i have done some workaround( queuing to cancel lout
this events ). Ideally on change event should be fired when the color
selection is done. Dont know if that's expected from the directive or not.

regards
Ari

**Comment by ruhley** [comment]
I have implemented a solution at commit https://github.com/ruhley/angular-color-picker/commit/88a00de568938897fa2dbd6e0def6dff2108eb15 and release in [v0.8.0](https://github.com/ruhley/angular-color-picker/releases/tag/v0.8.0). 

Tell me if it works well or not

**Comment by arindrajitb** [comment]
Brilliant genius! It works like charm.
Really appreciate your quick update on this.

thanks and regards
Ari
