### ISSUE TITLE
need a link to tinycolor, since there are multiple projects polluting the namespace

### ISSUE THREAD

**Issue by furiousOyster** [ruhley/angular-color-picker#49]
I assume it is: https://github.com/bgrins/TinyColor

Which needs to be installed with: npm install tinycolor2 

doing the not-too-wild-a-guess npm install tinycolor will give the wrong package I presume.

**Comment by ruhley** [comment]
@furiousOyster You are correct that it is tinycolor2. I have published the latest version to npm and with it the proper dependencies. Hopefully there will be no more confusion.

**Comment by furiousOyster** [comment]
thank you!!
