### ISSUE TITLE
Remove bootstrap dependency

### ISSUE THREAD

**Issue by ruhley** [ruhley/angular-color-picker#52]
Lots of people are creating forks to remove bootstrap. I don't want the library to assume people want something that they don't want.

**Comment by Frank3K** [comment]
+1

Maybe someone who has made a fork can create a PR?

**Comment by ruhley** [comment]
Fixed in commit 6f48c7e8030059caf36a49a25cb976007e891ccc and release in [v1.0.0](https://github.com/ruhley/angular-color-picker/releases/tag/v1.0.0).
