### ISSUE TITLE
Content Security Policy breaks color picker

### ISSUE THREAD

**Issue by Frank3K** [ruhley/angular-color-picker#53]
When using a Content Security Policy ([CSP](https://docs.angularjs.org/api/ng/directive/ngCsp), [docs at MDN](https://developer.mozilla.org/en-US/docs/Web/Security/CSP)) without `unsafe-inline` for `style-src` the color picker does not work. This is because of the various `ng-attr-style` properties in the template.

The solution to this issue would be to remove the `ng-attr-style` attributes from the template and apply the styling using JS in the `link` function using [.css(properties)](https://docs.angularjs.org/api/ng/function/angular.element).

If you want I can try to make a PR to resolve this issue.

**Comment by ruhley** [comment]
Fixed in commit 2ef76023f227c3969ea61a53eec9b99f4203d267 and release in [v1.0.0](https://github.com/ruhley/angular-color-picker/releases/tag/v1.0.0).

**Comment by Frank3K** [comment]
Wow thanks!

For extra performance you could maybe move the `querySelector` + `angular.element()` outside the `$watches`.
