### ISSUE TITLE
Bower: mark unminified source as main sources

### ISSUE THREAD

**Issue by Frank3K** [ruhley/angular-color-picker#54]
In `bower.json` it is common to mark the unminified sources as `main` entries. See for example  [bower-material](https://github.com/angular/bower-material/blob/fad0c0d268c7b55c9701654e0890cc96a7f37066/bower.json) and [bower-angular](https://github.com/angular/bower-angular/blob/f476940293160a959422f5450550a6768e6dd6dd/bower.json).

This way plugins like [bower-main-files](https://github.com/ck86/main-bower-files) pick up the unminified sources, which can be useful for debugging. It is a common workflow to bundle all external plugins into a single `vendor.js`, which can be minified at once.

**Comment by ruhley** [comment]
Fixed in commit f3325b075ad791f59128879c98f6a3060aa43710 and release in [v1.0.1](https://github.com/ruhley/angular-color-picker/releases/tag/v1.0.1)
