### ISSUE TITLE
Transparency with hex format

### ISSUE THREAD

**Issue by pixedd** [ruhley/angular-color-picker#55]
Hello, is there a way to get transparency with hex format ?

Currently I can get that, by using color-picker-format="rgb" and color-picker-alpha="true", however I would like to keep an hex format ?

Thanks !

**Comment by ruhley** [comment]
Hex does not cater for transparency. However that is what Hex8 was created for.

**Comment by celluj34** [comment]
Sorry to necro this thread, but it's very relevant to my interests.

I have a requirement to display a HEX editor with an available transparency/opacity selector. On the back end, I want to convert it to RGBA, but HEX is "more user friendly". Would it be possible to display the selector and provide the opacity value on the onChange event?

**Comment by ruhley** [comment]
If you want to display hex with opacity then you will need to select hex8. Then in the `onChange` event you can use tinycolor to convert it to rgba:

```js
var rgb_object = tinycolor('#36A193D2').toRgb();
var rgb_string = tinycolor('#36A193D2').toRgbString();
```

Tinycolor should already be imported as a dependency of this package.

**Comment by celluj34** [comment]
Awesome. Good enough for me! Thanks!

Joseph Cellucci
Software Developer
ITA Group
celluj34@gmail.com
