### ISSUE TITLE
bower intall - empty folder `themes`

### ISSUE THREAD

**Issue by AnatoliyLitinskiy** [ruhley/angular-color-picker#57]
I used

```bash
bower install angularjs-color-picker --save
```

after installation was finished I found that folder
`dist/themes`
is empty, so

```html
<!-- only include if you use bootstrap -->
<link rel="stylesheet" href="bower_components/angular-color-picker/dist/themes/angularjs-color-picker-bootstrap.min.css" />
```
can't be used

**Comment by ruhley** [comment]
Fixed in commit 1228dc584e1f968c40619c467474175dc2b102df and released in [v1.0.2](https://github.com/ruhley/angular-color-picker/releases/tag/v1.0.2). Please reopen the ticket if the problem persists.
