### ISSUE TITLE
Chosen color doesn't seem to match swatch

### ISSUE THREAD

**Issue by daric81** [ruhley/angular-color-picker#6]
Really like this project but not the color selection and swatch match.  After choosing a color, the swatch colour seems slightly lighter than what you have selected.  Has anyone else noticed this? Or if its just my eyes then let me know.

**Comment by ruhley** [comment]
I have noticed this to and it has always bothered me. The swatch in the text box is the correct colour. If you look at the [css](https://github.com/ruhley/angular-color-picker/blob/master/angularjs-color-picker.css#L143) I need a newer base64 for the background image that more correctly aligns with the swatch.

**Comment by daric81** [comment]
So its not just me :) 
Looking at the projects angular minicolors (and jquery-minicolors), it seems their color picker doesnt have the same issue. I'm sure you've probably already thought of this but it might be worth seeing what   differs in their color picker, or use the base64 from there  if thats the issue.

**Comment by ruhley** [comment]
I have just published v0.3.1. Can you please tell me if that improves it.

**Comment by daric81** [comment]
I haven't integrated it into my project yet, but looks good to me from the sample page :thumbsup:
