### ISSUE TITLE
color is not correct after model was set to undefined 

### ISSUE THREAD

**Issue by jbjumbojb** [ruhley/angular-color-picker#62]
![image](https://cloud.githubusercontent.com/assets/682524/14100637/1c232816-f5b9-11e5-8daa-f94f267f1ced.png)

example http://plnkr.co/edit/FznZuypDfawYP6CWcTqv?p=preview

**Comment by ruhley** [comment]
Fixed in commit 202cdc50fcedab44d357a101f0a468304d105b13 and released in [v1.0.3](https://github.com/ruhley/angular-color-picker/releases/tag/v1.0.3)
