### ISSUE TITLE
How to edit initial color value?

### ISSUE THREAD

**Issue by kunalvirk** [ruhley/angular-color-picker#63]
Great plugin!!!

How can I set the initial color value (by default it is white eg. rgb(255, 255, 255)).?
I'm also using alpha.

Till I tried  ng-init="TextColor='rgb(35, 16, 16)'" &  data-ng-init="TextColor='rgb(35, 16, 16)'", but that didn't work.

**Comment by Tim-Intellipharm** [comment]
The color value is set in the `ng-model` attribute. If you set the variable for that attribute it should set the initial color value.

If that is not what you need then could you post more of your code to help me try and find you a solution.

**Comment by ruhley** [comment]
The color value is set in the ng-model attribute. If you set the variable for that attribute it should set the initial color value.

If that is not what you need then could you post more of your code to help me try and find you a solution.
