### ISSUE TITLE
How to config requireJS to load tinycolor.js and angularjs-color-picker.js

### ISSUE THREAD

**Issue by andyandox** [ruhley/angular-color-picker#66]
How to config requireJS to load tinycolor.js and angularjs-color-picker.js.Thanks

**Comment by andyandox** [comment]
I find that when I using requireJS to load tinycolor.js and angularjs-color-picker.js.Some errors will happen, it tip that tinycolor is not defined in angularjs-color-picker.js.I can sure that tinycolor.js is load before angularjs-color-picker.js.But, when I using tag <script src='../tinycolor.js'> to load tinycolor.js and angularjs-color-picker use requireJS to load, everything is normal.So what happen?Does tinycolor not support RequireJS?Thanks~

**Comment by ruhley** [comment]
Can you post your code where you are including angularjs-color-picker.js

**Comment by andyandox** [comment]
@ruhley Sure,the code in main.js is like that `require.config({
	baseUrl:'../../js',
	paths: {
		//app
		'app':'libs/angular/app',
		// angular
		'angular': 'libs/angular/angular.min',
		// angular-ui
		'router': 'libs/angular/angular-ui-router.min',
		'tinycolor':'libs/color-picker/tinycolor.js',
		'colorPicker':'libs/color-picker/angularjs-color-picker.min'
	},
	shim: {
		// angular
		'angular': {
			exports: 'angular'
		},
		// angular-ui
		'router': ['angular'],
		'app':['router'],
		'tinycolor':['angular'],
		'colorPicker':['angular']
	}
});

// 初始化bnApp模块
require(['app', 'colorPicker'], function(){
	angular.bootstrap(document, ['bnApp']);
});`
and when I open the page which use '<color-picker>' tag, the error `ReferenceError: tinycolor is not defined
    at m.c.hueUpdate (angularjs-color-picker.min.js:34)` will show in browser`s console.

**Comment by ruhley** [comment]
I must admit I have never used RequireJS, but try `require(["app", "tinycolor, "colorPicker"], function(){` instead.

**Comment by andyandox** [comment]
Thanks.I have tried that, but nothing can help.I wonder that tinycolor.js is just a general javascript file,isn`t it?And I defined a simple javascript file which just has only a simple function that alert something, and it can run normally whereever I use.

**Comment by ruhley** [comment]
As this seems to be a RequireJS configuration issue and not a problem with this library, I am closing this ticket. Sorry I couldn't help you.

**Comment by andyandox** [comment]
fine

**Comment by pevers** [comment]
I found this issue because I struggled with the same problem. Tinycolor doesn't register on the window object if you use a loader, see https://github.com/bgrins/TinyColor/issues/122.

```js
require(['tinycolor'], function(tinycolor) {
    window.tinycolor = tinycolor;
});
```

Will fix it.

**Comment by andyandox** [comment]
@pevers thanks
