### ISSUE TITLE
Panel width is wrong when alpha is enabled

### ISSUE THREAD

**Issue by kamilbrk** [ruhley/angular-color-picker#67]
Nitpicking really, but when alpha mode is available, main panel width should be increased to 194px from the default 173px. This isn't done automatically due the usage of absolute positioning.

You can see that easily due to the box-shadow and dev tools highlight.

![colorpicker-alpha-width-194 mov](https://cloud.githubusercontent.com/assets/591349/14880663/02c5c8a2-0d28-11e6-8f0a-10561fa31cec.gif)

Workaround for now:
`<color-picker ng-class="{ 'acp-67': modal.colorFormat !== 'hex' }">`
`.acp-67 .color-picker-wrapper .color-picker-panel { width: 194px; }`

I just made a fork with minimal changes:
- Moved from absolute top/left to relative with float:left and 1px padding around
- Shifted order of the elements in the template, since they're floated to left now
- Removed my hacky width:194px from example-65 (the issue I submitted recently)

Tested it with my setup (same as on #65) and all 4 positions (top left, top right, etc.) on Chrome 52 - seems ok, but I would appreciate a proper test anyway, it's entirely possible I broke something, but there are no tests in grunt config.

I have only committed source files, I'll leave the grunt build, version bump, etc. to you.

See PR #68

**Comment by ruhley** [comment]
Thanks for the pull request. Looks good. Released in [v1.0.7](https://github.com/ruhley/angular-color-picker/releases/tag/v1.0.7)
