### ISSUE TITLE
Alpha slider regression in v1.0.6

### ISSUE THREAD

**Issue by kamilbrk** [ruhley/angular-color-picker#69]
This is related to #65 

Setup:

```
modal.color = 'rgb(255, 255, 255)';
modal.colorFormat = 'hex';
```
```
<color-picker
  ng-model="modal.color"
  color-picker-format="modal.colorFormat"
  color-picker-swatch-pos="'right'"
  color-picker-swatch-bootstrap="false"
></color-picker>
```

v1.0.5

1. Activate the picker - alpha slider visible, but obviously doesn't work
2. Switch from HEX to RGB
3. Change transparency
4. Switch from RGB to HEX
5. Change color - alpha is reset to 100% (obviously, good thing)
![acp-1 0 5 mov](https://cloud.githubusercontent.com/assets/591349/14886240/b7e27676-0d47-11e6-8c6e-d94d57ee4a95.gif)

v1.0.6

1. Activate the picker - alpha slider visible, but obviously doesn't work
2. Switch from HEX to RGB
3. Change transparency
4. Switch from RGB to HEX
5. Alpha slider is gone - which is a good thing
6. Switch from HEX to RGB
7. Alpha slider is still gone, transparency is dead from now on

![acp-1 0 6 mov](https://cloud.githubusercontent.com/assets/591349/14886242/b8fc3d6c-0d47-11e6-83be-59120cf1385a.gif)

I hope is clear enough to understand.

Workarounds:

1. ```color-picker-alpha="modal.colorFormat !== 'hex'"```, or
2. Provide extra alpha state toggle for the end-user, or
3. Watch for format change and update the alpha state manually

It seems like alpha slider state should be determined on the first init and be updated on every format change. Right now (v1.0.6) it gets disabled once when you switch to HEX but it's stuck afterwards - unless we trigger c-p-alpha to true.

So, ideally, in both _first_ steps above, alpha slider should be disabled and toggled on each format change automatically. That is, unless c-p-alpha directive is present.

Now, question is, should that be sorted automatically by the lib or should devs do that themselves? First workaround does the job, to be honest.

Nitpicking again, sorry for that. I like to think it's for the sake of good UX - user wouldn't like to toggle that option on and on again after changing hex format to others.

Plunker: https://plnkr.co/edit/tRiueSFrxVrBHYeWvnJc?p=preview (comment out v1.0.5/6 in head)

**Comment by ruhley** [comment]
I am no longer overriding the `color-picker-alpha` parameter and instead just added `format !== 'hex'` in the template. Fixed in commit 513961d838de5f34a403e5b18dad6408a539e797 and released in [v1.0.7](https://github.com/ruhley/angular-color-picker/releases/tag/v1.0.7)
