### ISSUE TITLE
Bug when you copy & paste the color

### ISSUE THREAD

**Issue by yuliaz** [ruhley/angular-color-picker#71]
Hi,
I found a bug, when you try to copy & paste a color from input to other input it's not set the color (When you checked whats your real color on console log you will see color that been before in the input, and not the correct).
I checked it and its happened because copy&paste action don't send a event, and the others action (when you chose the color from the picker) its send a mouse event.

**Comment by ruhley** [comment]
Using `color-picker-on-change` and `$scope.$watch` and outputting the value onto the page `{{color}}` it updates when pasting a value into the text box. The event for `color-picker-on-change` is `undefined`, but it still works. Are you pasting a valid color?

**Comment by yuliaz** [comment]
Yes, Its outputting the value into the page {{color}} but real it's not send the updated color using angular form. If you try to create a simple angular form, and put there 2 color picker fields, when you copy the value from first color picker to second , on second colorpicker it will sent you the default color of the color picker and not the correct, this happens because he can find a event for ctrl+v.

**Comment by ruhley** [comment]
Can you create a plunkr or jsfiddle with an example?

**Comment by ruhley** [comment]
I cannot replicate this issue on v1.1.2, so I am closing this issue. Please reopen with an plunkr example if it still occurs for you.
