### ISSUE TITLE
CSS Broken in 1.0.7

### ISSUE THREAD

**Issue by paulking00** [ruhley/angular-color-picker#73]
Hi there,

Awesome project! Thank you!!

In the latest release the CSS seems broken for the following settings when the swithe pops up.

It works fine in 1.0.3

  <color-picker ng-model="vm.backgroundColour"
                color-picker-format="'hex'"
                color-picker-swatch-only="true"
                color-picker-alpha="false"
                color-picker-pos="'top left'"></color-picker>

Fixed with a position: absolute and a little positioning.

Cheers,
Paul

**Comment by paulking00** [comment]
Fixed.

**Comment by ruhley** [comment]
Released [v1.1.0](https://github.com/ruhley/angular-color-picker/releases/tag/v1.1.0)
