### ISSUE TITLE
Input element for color-picker-input-swatch brings up keyboard on mobile

### ISSUE THREAD

**Issue by paulking00** [ruhley/angular-color-picker#74]
Hi Ruhley,

I'm using your color-picker for mobile devices with these params:

`
  <color-picker ng-model="vm.backgroundColour"
                color-picker-format="'hex'"
                color-picker-swatch-only="true"
                color-picker-alpha="false"
                color-picker-pos="'top left'"></color-picker>
`

Since the ng-model for the swatch is in an input element, clicking on the swatch to bring up the colour palette causes the mobile keyboard to pop up and then dissappear quickly.

Can the input be swapped out for a span or a div or something else?

I'm not sure if it will be a simple swap or not, but I just wanted to let you know.

Cheers,
Paul.

**Comment by ruhley** [comment]
Fixed in commit b5cc3083ccb6e2ff638d080f70056ac810f9e73d and released in [v1.1.1](https://github.com/ruhley/angular-color-picker/releases/tag/v1.1.1)

**Comment by paulking00** [comment]
Awesome works great!

Also, big props for the inline mode in 1.1.1

Thats exactly what I needed!!

I manually also hide the input completely (display none), but that could also be an option in your directive.

Cheers,
Paul.
