### ISSUE TITLE
The picker appears twice in 1.0.7 on Firefox

### ISSUE THREAD

**Issue by rasler** [ruhley/angular-color-picker#75]
![capture](https://cloud.githubusercontent.com/assets/1257634/15010405/211282fa-11ec-11e6-859d-8b54e61d7aa8.PNG)

Firefox v45.0.2 on Windows 7.1

**Comment by ruhley** [comment]
See #70 - I believe this is a duplicate

**Comment by ruhley** [comment]
Released [v1.1.0](https://github.com/ruhley/angular-color-picker/releases/tag/v1.1.0)
