### ISSUE TITLE
Bootstrap styles

### ISSUE THREAD

**Issue by xak2000** [ruhley/angular-color-picker#76]
I think we should remove changes in bootstrap styles (`angularjs-color-picker-bootstrap.less`) introduced in 2e50e2f6f41f342744f5ce634d12da86290d01f5.

```
.form-inline {
    .color-picker-wrapper {
        width: auto;
        display: inline-block;
        vertical-align: middle;
    }
}
```

This style doesn't take into account bootstrap's media-queries. Native bootstrap controls change their stacking and width depending on screen size using `@media (min-width: @screen-sm-min)`. We can't do this in bootstrap theme file because we don't know value of `@screen-sm-min` variable. By default it is 768px. But user can change it in his local bootstrap. So we can't just guess.

Also this style rule breaks "correct" bootstrap form-inline DOM structure, when controls live inside `form-group` divs, like in bootstrap docs:
```
<form class="form-inline">
  <div class="form-group">
    <label for="exampleInputName2">Name</label>
    <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">Email</label>
    <input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">
  </div>
  <button type="submit" class="btn btn-default">Send invitation</button>
</form>
```

When we place `color-picker` element inside `form-group`, then all works fine **without** addition, introduced in 2e50e2f6f41f342744f5ce634d12da86290d01f5. Responsive layout works fine. But with this addition layout is broken on width<768px (@screen-sm-min).

[Plunker](https://plnkr.co/edit/EnSEpA2VuWGoq96fX616?p=preview) demonstrating it. Try to change preview frame width to make it more or less than 768px. You will see incorrect width of color-picker when width is less than 768px. It should be 100%. Then try to uncomment css style rules which remove introduced change.

You added this rules because I used them in my project. But in my project I used bootstrap `form-inline` incorrectly. I used `form-control`s just inside form. But from bootstrap docs it should be placed inside `form-group`s to correctly layout on small screen widths.

**Comment by ruhley** [comment]
Fixed in commit 246a687cb5e333d3bec1891b6b6d8d94da8c4026 and released in [v1.1.2](https://github.com/ruhley/angular-color-picker/releases/tag/v1.1.2)
