### ISSUE TITLE
Do not include minified files in main property of bower.json

### ISSUE THREAD

**Issue by hzpz** [ruhley/angular-color-picker#8]
As mentioned in the [bower.json specification](https://github.com/bower/bower.json-spec#main), you should not include minified files in the main property. This also seems to affect wiredep in a way that it won't inject any dependencies of angular(js)-color-picker at all. I used the following override to make it work:

    "overrides": {
      "angularjs-color-picker": {
        "main": [
          "angularjs-color-picker.js",
          "angularjs-color-picker.css"
        ]
      }
    }

**Comment by ruhley** [comment]
Fixed in b2ad5db47cc1db2d0033c3e239b4c303a46111c6 and released in [v0.3.3](https://github.com/ruhley/angular-color-picker/releases/tag/v0.3.3).

Thanks for the great pickups.
