### ISSUE TITLE
Internet Explorer 11: clicking the swatch does not toggle the visibility of the panel

### ISSUE THREAD

**Issue by val-samonte** [ruhley/angular-color-picker#80]
$scope.find('.color-picker-input')[0].focus(); does not trigger $scope.show. I fixed this temporarily by adding $scope.show() just below the line.

**Comment by val-samonte** [comment]
Additional information: check out jquery docs about .focus https://api.jquery.com/focus/:

"The focus event does not bubble in Internet Explorer. Therefore, scripts that rely on event delegation with the focus event will not work consistently across browsers. As of version 1.4.2, however, jQuery works around this limitation by mapping focus to the focusin event in its event delegation methods, .live() and .delegate()."

**Comment by ruhley** [comment]
I am using Internet Explorer 11 on windows 10 and cannot replicate this bug. When I click on the swatch, the input gets focus and the picker pops up. Can you please supply more details about how to encounter this bug.

**Comment by val-samonte** [comment]
@ruhley sorry, will provide the steps to replicate as soon as possible. i also have the same OS, but my initial findings is that the focus didn't trigger.

**Comment by ruhley** [comment]
@val-samonte I will close this bug, but feel free to re-open it if you manage to find the problem
