### ISSUE TITLE
Initial value is partially set

### ISSUE THREAD

**Issue by jozsi** [ruhley/angular-color-picker#81]
Hello,

This should describe the problem:
![image](https://cloud.githubusercontent.com/assets/840815/16127092/a4bc35cc-3403-11e6-8a76-c5621e46c52d.png)

I have a value set in the model, but until the first user interaction it doesn't properly position the `color-picker-picker` on the `color-picker-grid`, respectively the `color-picker-slider` on the `color-picker-hue`.

**Comment by c00lankit** [comment]
jozsi  can u give me color picker code.... Ankit.rajpoot93.ar@gmail.com

**Comment by ruhley** [comment]
Fixed in commit 11b3d428c5081b4e3ba9a1aecf95038841d291ae and released in [v1.1.5](https://github.com/ruhley/angular-color-picker/releases/tag/v1.1.5)

**Comment by jozsi** [comment]
@ruhley: thanks, but it only partially fixes the problem.
![image](https://cloud.githubusercontent.com/assets/840815/16224476/e081994e-37aa-11e6-89a2-0db0b92c4841.png)

As you can see, the slider doesn't seem to work.

**Comment by ruhley** [comment]
@jozsi Are you able to create a jsfiddle or plunkr to replicate this problem as it works for me. Also which browser are you using?

**Comment by jozsi** [comment]
I've created a [Plunkr](https://plnkr.co/edit/ZqHqfJpllCi8JA9FQMnN?p=preview) that replicates the problem. I'm using Chrome.

**Comment by ruhley** [comment]
Fixed in commit 004b66e3f27b7e2776e17679638e93bf5affe3a6 and released in [v1.1.6](https://github.com/ruhley/angular-color-picker/releases/tag/v1.1.6)

**Comment by jozsi** [comment]
It works as expected now, thank you!

**Comment by jozsi** [comment]
I found yet another case with wrong initials values, however, I didn't have time to create a plunker:
![image](https://cloud.githubusercontent.com/assets/840815/16383312/4554a5c8-3c8d-11e6-923a-34b39b4c5e6e.png)

**Comment by jozsi** [comment]
Updated the [Plunkr](https://plnkr.co/edit/ZqHqfJpllCi8JA9FQMnN?p=preview) - it happens when inline is `true` and the value is set directly, not via `$timeout`.

**Comment by ruhley** [comment]
Fixed in commit 5622dc6a15becde7ba362aa1c5df1d525968e05b and released in [v1.1.7](https://github.com/ruhley/angular-color-picker/releases/tag/v1.1.7)

**Comment by jozsi** [comment]
Looks good. Has a small flicker (it starts in a position then jumps to the correct position), but that might be caused by my app. Thanks!
