### ISSUE TITLE
Allow onOpen and onClose events

### ISSUE THREAD

**Issue by zaalbarxx** [ruhley/angular-color-picker#83]
Hi!
I think it would be a good idea to allow user handling event like open and close, for example I'd like to show bar with recently selected colors at the bottom of picker, but currently I have no possibility to check if the picker is opened or closed. We could create two new attributes on directive or allow user to provide a model which would change when picker is opened or closed. What do you think about this ? I think it is rather easy to implement as it's just a matter of adding a couple lines of code.

**Comment by zaalbarxx** [comment]
I created a pull request, let me know if you are satisfied with it. Thanks !
https://github.com/ruhley/angular-color-picker/pull/84

**Comment by ruhley** [comment]
I think exposing an api would be better. I will put it together as soon as possible.

**Comment by ruhley** [comment]
I have created [v2.0.0](https://github.com/ruhley/angular-color-picker/releases/tag/v2.0.0) with some large changes including exposing an api.
