### ISSUE TITLE
onBlur/onClose event

### ISSUE THREAD

**Issue by Lukinos** [ruhley/angular-color-picker#87]
Hello,

Thank you for your update 2.1.0! But I still have some little issues.

* The onBlur event seems not trigger anymore.
* The onClose does not work on Firefox 48 (i.e `ReferenceError: event is not defined`)

You can easily reproduce them by using your `01-simple.html`.

**Comment by ruhley** [comment]
Fixed in commit 2c908726c305312f2837532e0d631cd61ed94ebf and released in [v2.1.1](https://github.com/ruhley/angular-color-picker/releases/tag/v2.1.1)
