### ISSUE TITLE
Depend on angular rather than angularjs

### ISSUE THREAD

**Issue by hzpz** [ruhley/angular-color-picker#9]
angular(js)-color-picker depends on angularjs instead of just angular. I am not sure how this even works because the [bower.io search](http://bower.io/search/?q=angularjs) does not return a package named angularjs. The main problem however is, that every other angular related package I have used so far depends on angular which results in two (possibly different) angular versions as dependencies. This is especially an issue if you use tools like [wiredep](https://github.com/taptapship/wiredep) to automatically inject dependencies. If there is no reason to use angularjs I would appreciate it, if the dependency was changed to angular instead.

**Comment by ruhley** [comment]
Fixed in b2ad5db47cc1db2d0033c3e239b4c303a46111c6 and released in [v0.3.3](https://github.com/ruhley/angular-color-picker/releases/tag/v0.3.3).

Thanks for the great pickups.
