### ISSUE TITLE
Unable to add multiple color pickers. 

### ISSUE THREAD

**Issue by adflictusk** [ruhley/angular-color-picker#97]
Hi!

I'm trying to add multiple color pickers in a dialog, but the .sprite doesn't change according to the color chosen on the right panel visually ie. it's always displaying the black and white spectrum. The color code seems to be working fine though. Advice, please? Thanks in advance! 

<img width="598" alt="untitled" src="https://cloud.githubusercontent.com/assets/12406291/17235791/6f5cda5a-5576-11e6-8fce-5851d693a9e2.png">

**Comment by ruhley** [comment]
@adflictusk Can you give me more information on your environment? OS, browser, angular version, color picker version

**Comment by adflictusk** [comment]
I'm using Angular v1.5.5, color picker v2.2.0. Testing on Windows 10, Chrome.

**Comment by ruhley** [comment]
I cannot replicate this issue, you could always try upgrading to v2.3.0. Can you create a [plunker](https://plnkr.co/) replicating the issue?

**Comment by adflictusk** [comment]
I was able to fix the issue with v2.3.0! Thanks!
