### ISSUE TITLE
Is there any options for global config

### ISSUE THREAD

**Issue by dmitry-kostin** [ruhley/angular-color-picker#98]
to set all options in app config

**Comment by Tim-Intellipharm** [comment]
No, but the options object can be used on multiple color pickers. If you need this I can add it as a feature request

**Comment by ruhley** [comment]
No, but the options object can be used on multiple color pickers. If you need this I can add it as a feature request

**Comment by dmitry-kostin** [comment]
Yes for now i just use root scope for shared options, but it would be fine to have ability to configure through config, since the way i use is not very nice and uses rootScope

Also another feature i think is missing is to set model value through the api, for example: on startup I want all my inputs to be #fff, for now i get this behaviour a little bit tricky through on blur event

**Comment by ruhley** [comment]
@dmitry-kostin I have no experience creating a decorator before, so can you please review the commit 7b59c75b6c3e62c9554ebc12e9a22d382eeac3ca before I create a new release.

**Comment by ruhley** [comment]
Released in v2.4.0. View the updated documentation
