### ISSUE TITLE
build process: nodejs vs node

### ISSUE THREAD

**Issue by fhurta** [ruhley/angular-color-picker#99]
When I tried to build using `grunt build` I ended up with the following output:

	Running "notify:build" (notify) task

	Running "jshint:src" (jshint) task
	>> 4 files lint free.

	Running "jshint:grunt" (jshint) task
	>> 10 files lint free.

	Running "clean:build" (clean) task
	File created
	File created
	>> 1 path cleaned.

	Running "run:rollup" (run) task
	>> Error: spawn nodejs ENOENT
	Warning: non-zero exit code -4058 Use --force to continue.

	Aborted due to warnings.

After a while a figured out the problem is in `grunt/options/run.js` where the `cmd` was set to `nodejs`. After I changed it to `node`, the process run well.

**Comment by ruhley** [comment]
I can confirm that `node` and `nodejs` both work for me.
